'nav_sat':
  'topic': '/gps_navsat'
  'script': 'start_nav_sat.sh'
  'method': 'topic'
  'topic_type': NavSatFix
  'timeout': 5.0

'drive':
  'topic': '/odom_wheel'
  'script': 'start_drive.sh'
  'method': 'topic'
  'topic_type': Odometry
  'timeout': 5.0

'lidar':
  'topic': '/scan'
  'script': 'start_lidar.sh'
  'method': 'topic'
  'topic_type': LaserScan
  'timeout': 5.0

'imu':
  'topic': '/imu'
  'script': 'start_imu.sh'
  'method': 'topic'
  'topic_type': Imu
  'timeout': 5.0

'icp':
  'topic': '/odom_lidar'
  'script': 'start_lidar_icp.sh'
  'method': 'topic'
  'topic_type': Odometry
  'timeout': 5.0
  
'ekf_inertial': 
  'topic': '/odom_inertial'
  'script': 'start_ekf_inertial.sh'
  'method': 'topic'
  'topic_type': Odometry
  'timeout': 5.0
  
'map_inertial':
  'topic': '/map'
  'script': 'start_map_inertial.sh'
  'method': 'topic'
  'topic_type': OccupancyGrid
  'timeout': 2.0
  
'map_local':
  'topic': '/map_pose'
  'script': 'start_map_localization.sh'
  'method': 'topic'
  'topic_type': PoseStamped
  'timeout': 2.0
  
'roscore':
  'topic': '/system_diagnostics'
  'script': 'start_state_observer.sh'
  'method': 'none'
  'topic_type': Diagnostics
  'timeout': 2.0
  
'state_obs':
  'topic': '/system_diagnostics'
  'script': 'start_state_observer.sh'
  'method': 'node'
  'topic_type': Diagnostics
  'timeout': 2.0
  
'april_tags':
  'topic': '/tag_detections'
  'script': 'start_tag_detection.sh'
  'method': 'none'
  'topic_type': AprilTagDetectionArray
  'timeout': 2.0

'navigation':
  'topic': '/MOVE/local_costmap/costmap'
  'script': 'start_nav.sh'
  'method': 'topic'
  'topic_type': OccupancyGrid
  'timeout': 5.0

'map_tf':
  'topic': '/TF_MAP'
  'script': 'start_map_tf.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 5.0
  
'realsense':
  'topic': '/camera/depth/color/points'
  'script': 'start_realsense.sh'
  'method': 'node'
  'topic_type': PointCloud2
  'timeout': 5.0
  
'video':
  'topic': '/camera/depth/color/points'
  'script': 'start_realsense.sh'
  'method': 'none'
  'topic_type': PointCloud2
  'timeout': 5.0

'gps_driver':
  'topic': '/gps_navsat_raw'
  'script': 'start_gps_driver.sh'
  'method': 'topic'
  'topic_type': NavSatFix
  'timeout': 5.0
  
'gps_conv':
  'topic': '/gps_fix'
  'script': 'start_gps_converter.sh'
  'method': 'topic'
  'topic_type': GPSFix 
  'timeout': 5.0
  
'control_global':
  'topic': '/controller_check'
  'script': 'start_control_global.sh'
  'method': 'topic'
  'topic_type': Float64
  'timeout': 5.0

'avoidance':
  'topic': '/obstacles'
  'script': 'start_avoidance.sh'
  'method': 'node'
  'topic_type': PointCloud2
  'timeout': 5.0
  
'explore':
  'topic': ''
  'script': 'start_exploration_server.sh'
  'method': 'node'
  'topic_type': None
  'timeout' : 5.0
  
'rosbridge':
  'name': 'rosbridge'
  'topic': 9090
  'script': 'start_rosbridge.sh'
  'method': 'websocket'
  'topic_type': None
  'timeout' : 5.0