'sitl': 
  'topic': '/odom_wheel'
  'script': 'start_gazebo_sitl.sh'
  'method': 'node'
  'topic_type': Odometry
  'timeout': 0.5

'firmware': 
  'topic': '/odom_wheel'
  'script': 'start_sitl_firmware.sh'
  'method': 'node'
  'topic_type': Odometry
  'timeout': 0.5

'nav_sat':
  'topic': '/gps_navsat'
  'script': 'start_nav_sat.sh'
  'method': 'node'
  'topic_type': NavSatFix
  'timeout': 0.5

'icp':
  'topic': '/odom_lidar'
  'script': 'start_lidar_icp.sh'
  'method': 'node'
  'topic_type': Odometry
  'timeout': 0.5

'pc_conv':
  'topic': '/scan_cloud'
  'script': 'start_pc_convert.sh'
  'method': 'topic'
  'topic_type': LaserScan
  'timeout': 5.0
  
'ekf': 
  'topic': '/odom'
  'script': 'start_ekf.sh'
  'method': 'node'
  'topic_type': Odometry
  'timeout': 0.5
  
'map':
  'topic': '/map'
  'script': 'start_map.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5
  
'amcl':
  'topic': '/map'
  'script': 'start_amcl.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 2.0
  
'state_obs':
  'topic': '/system_diagnostics'
  'script': 'start_state_observer.sh'
  'method': 'node'
  'topic_type': Diagnostics
  'timeout': 2.0
  
'april_tags':
  'topic': '/tag_detections'
  'script': 'start_tag_detection.sh'
  'method': 'node'
  'topic_type': AprilTagDetectionArray
  'timeout': 2.0
  
'map_local':
  'topic': '/map_pose'
  'script': 'start_map_localization.sh'
  'method': 'node'
  'topic_type': PoseStamped
  'timeout': 0.5

'navigation':
  'topic': '/MOVE/local_costmap/costmap'
  'script': 'start_nav.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5

'map_tf':
  'topic': '/TF_MAP'
  'script': 'start_map_tf.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5

'avoidance':
  'topic': '/obstacles'
  'script': 'start_avoidance.sh'
  'method': 'node'
  'topic_type': PointCloud2
  'timeout': 0.5
  
'nav_inertial':
  'topic': '/MOVE_INERTIAL/local_costmap/costmap'
  'script': 'start_nav_inertial.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5
  
'gps_driver':
  'topic': '/gps_fix'
  'script': 'start_gps_driver_gazebo.sh'
  'method': 'node'
  'topic_type': GPSFix
  'timeout': 0.5
  
'gps_driver_airsim':
  'topic': '/gps_fix'
  'script': 'start_gps_driver_airsim.sh'
  'method': 'node'
  'topic_type': GPSFix
  'timeout': 0.5
  
'gps_conv':
  'topic': '/gps_navsat'
  'script': 'start_gps_converter.sh'
  'method': 'node'
  'topic_type': NavSatFix
  'timeout': 0.5

'gps_init':
  'topic': '/local_xy_origin'
  'script': 'start_gps_initializer.sh'
  'method': 'node'
  'topic_type': PoseStamped
  'timeout': 0.5
  
'ekf_global':
  'topic': '/odom_global'
  'script': 'start_ekf_global.sh'
  'method': 'node'
  'topic_type': Odometry
  'timeout': 0.5
  
'nav_global':
  'topic': '/MOVE_GLOBAL/local_costmap/costmap'
  'script': 'start_nav_global.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5
  
'map_global':
  'topic': '/map_global'
  'script': 'start_map_global.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5
  
'control_global':
  'topic': '/controller_check'
  'script': 'start_control_global.sh'
  'method': 'node'
  'topic_type': Float64
  'timeout': 0.5
  
'avoid_inertial':
  'topic': '/obstacles'
  'script': 'start_avoidance_inertial.sh'
  'method': 'node'
  'topic_type': PointCloud2
  'timeout': 0.5
  
'avoid_global':
  'topic': '/obstacles'
  'script': 'start_avoidance_global.sh'
  'method': 'node'
  'topic_type': PointCloud2
  'timeout': 0.5
  
'nav_trans':
  'topic': '/MOVE_TRANS/local_costmap/costmap'
  'script': 'start_nav_trans.sh'
  'method': 'node'
  'topic_type': OccupancyGrid
  'timeout': 0.5
  
'rviz':
  'topic': ''
  'script': 'start_rviz.sh'
  'method': 'none'
  'topic_type': None
  'timeout': 0.5
  
'rviz_inertial':
  'topic': ''
  'script': 'start_rviz_inertial.sh'
  'method': 'none'
  'topic_type': None
  'timeout': 0.5
  
'rviz_trans':
  'topic': ''
  'script': 'start_rviz_transition.sh'
  'method': 'none'
  'topic_type': None
  'timeout': 0.5
  
'rviz_global':
  'topic': ''
  'script': 'start_rviz_global.sh'
  'method': 'none'
  'topic_type': None
  'timeout': 0.5
  
'explore':
  'topic': ''
  'script': 'start_exploration_server.sh'
  'method': 'node'
  'topic_type': None
  'timeout' : 5.0

'roscore':
  'topic': '/rosout'
  'script': 'start_roscore.sh'
  'method': 'node'
  'topic_type': None
  'timeout': 2.0
  
'rosbridge':
  'name': 'rosbridge'
  'topic': 9090
  'script': 'start_rosbridge.sh'
  'method': 'websocket'
  'topic_type': None
  'timeout' : 5.0